Ttree:
  OutOfBandRendering:
    presets: []
    # 'test':
    #   path: 'root<Neos.Fusion:Case>/fallback<Neos.Fusion:Matcher>/element<Ttree.Strapping:Document.DefaultLayout>/body<Neos.Fusion:Case>/documentFinder<Neos.Fusion:Matcher>/element<Ttree.Extranet:Document.Staff>/renderer<Ttree.Website:Components.Template.Content>/content'

Neos:
  Neos:
    fusion:
      autoInclude:
        Ttree.OutOfBandRendering: true
